[lint]
ignore = [
  # Ignore module import not at top of file
  "E402",
  # Annoying style checks
  "E7",
  # Keep nested with statements
  "SIM117",
  # Keep nested if statements
  "SIM102",
  # Allow lambdas in loops
  "B023",
]
[lint.isort]
combine-as-imports = true
